// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortExtract() {
  return window['go']['main']['App']['AbortExtract']();
}

export function ClearLogin() {
  return window['go']['main']['App']['ClearLogin']();
}

export function ExportResults() {
  return window['go']['main']['App']['ExportResults']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Login(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3, arg4);
}

export function RefreshCaptcha() {
  return window['go']['main']['App']['RefreshCaptcha']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function StartExtract(arg1, arg2) {
  return window['go']['main']['App']['StartExtract'](arg1, arg2);
}
