// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortExtract():Promise<Record<string, any>>;

export function ClearLogin():Promise<Record<string, any>>;

export function ExportResults():Promise<Record<string, any>>;

export function GetConfig():Promise<Record<string, any>>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function RefreshCaptcha():Promise<Record<string, string>>;

export function SelectFile():Promise<Record<string, string>>;

export function StartExtract(arg1:string,arg2:string):Promise<Record<string, any>>;
